#!/bin/bash
mv /tmp/betty/tmp/
#! /bin/bash
rm /tmp/betty/tmp/my_first_directory
#! /bin/bash
rm /tmp/betty/tmp/my_first_directory
#! /bin/bash
rm /tmp/betty/tmp/my_first_directory
#! /bin/bash
mv /tmp/betty/tmp/my_first_directory
